package co.unicauca.apptimarket.client.presentation;

import co.unicauca.apptimarket.client.access.Factory;
import co.unicauca.apptimarket.client.access.IProductAccess;
import co.unicauca.apptimarket.client.domain.services.ProductService;
import static co.unicauca.apptimarket.client.infra.Messages.successMessage;
import co.unicauca.apptimarket.commons.domain.Product;
import co.unicauca.apptimarket.commons.domain.carritoDTO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author WINDOWS
 */
public class frmCarrito extends javax.swing.JFrame {

    ArrayList<carritoDTO> objList;

    /**
     * Creates new form frmCarrito
     */
    //ArrayList<String> 
    public frmCarrito() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public frmCarrito(String prmCodigo, String prmNombre, String prmPrecio, int prmCantidad) {
        initComponents();
        setLocationRelativeTo(null);
        this.verTablaCarrito(prmCodigo, prmNombre, prmPrecio, prmCantidad);
    }

    DefaultTableModel objCarrito = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    frmCarrito(ArrayList<carritoDTO> objList) {
        initComponents();
        setLocationRelativeTo(null);
        this.objList = objList;
        this.verTablaCarrito();
    }

    //Mostrar datos en la tabla del pabel Registrar producto
    private void verTablaCarrito() {
        // TODO add your handling code here:
        tblCarrito.setModel(objCarrito);
        objCarrito.setNumRows(0);

        IProductAccess objService = Factory.getInstance().getProductService();

        ProductService objProductService = new ProductService(objService);

        Product objProduct;

        System.out.println("MIRANDO LISTA DEL CARRITO");

        try {

            for (int count = 0; count < objList.size(); count++) {
                objCarrito.setColumnIdentifiers(new Object[]{"Codigo", "Nombre", "Precio", "Cantidad"});
                objCarrito.insertRow(count, new Object[]{objList.get(count).getCodigo(), objList.get(count).getNombre(),
                    objList.get(count).getPrecio(), objList.get(count).getCantidad()});
            }

            // System.out.println("Desde Carrito\n Código: " + codigo + ", nombre: " + nombre + ", precio: " + precio);
            tblCarrito.setRowHeight(1, 30);

        } catch (Exception ex) {
            successMessage(ex.getMessage(), "Atención");
            return;
        }

    }

    public void verTablaCarrito(String codigo, String nombre, String precio, int cantidad) {
        // TODO add your handling code here:
        tblCarrito.setModel(objCarrito);
        objCarrito.setNumRows(0);

        IProductAccess objService = Factory.getInstance().getProductService();

        ProductService objProductService = new ProductService(objService);

        Product objProduct;

        System.out.println("MIRANDO LISTA DEL CARRITO");
        int count;
        try {

            for (count = 0; count < 10; count++) {
                objCarrito.setColumnIdentifiers(new Object[]{"Codigo", "Nombre", "Precio", "Cantidad"});
                objCarrito.insertRow(count, new Object[]{codigo, nombre, precio, cantidad});
            }

            System.out.println("Desde Carrito\n Código: " + codigo + ", nombre: " + nombre + ", precio: " + precio);

            tblCarrito.setRowHeight(1, 30);

        } catch (Exception ex) {
            successMessage(ex.getMessage(), "Atención");
            return;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCarrito = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnCVolver = new javax.swing.JButton();
        btnCPagar = new javax.swing.JButton();
        btnCSalir = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblCarrito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblCarrito);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Carrito de compras.");

        btnCVolver.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnCVolver.setText("Volver");
        btnCVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCVolverActionPerformed(evt);
            }
        });

        btnCPagar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnCPagar.setText("Pagar");
        btnCPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCPagarActionPerformed(evt);
            }
        });

        btnCSalir.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnCSalir.setText("Salir");
        btnCSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCSalirActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCVolver)
                        .addGap(79, 79, 79)
                        .addComponent(btnEliminar)
                        .addGap(95, 95, 95)
                        .addComponent(btnCPagar)
                        .addGap(80, 80, 80)
                        .addComponent(btnCSalir))
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 761, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(61, 61, 61)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCVolver)
                    .addComponent(btnCPagar)
                    .addComponent(btnCSalir)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(147, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(397, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCVolverActionPerformed
        // TODO add your handling code here:
        new frmCliente().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCVolverActionPerformed

    private void btnCPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCPagarActionPerformed
        // TODO add your handling code here:

        new frmPago(objList).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCPagarActionPerformed

    private void btnCSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnCSalirActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int fila = tblCarrito.getSelectedRow();
        if (fila >= 0) {
            objCarrito.removeRow(fila);
            objList.remove(fila);
        } else {
            JOptionPane.showMessageDialog(null, "Seleccionar Fila");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCarrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCarrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCarrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCarrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCarrito().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCPagar;
    private javax.swing.JButton btnCSalir;
    private javax.swing.JButton btnCVolver;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblCarrito;
    // End of variables declaration//GEN-END:variables
}
