
package co.unicauca.apptimarket.client.presentation;

import co.unicauca.apptimarket.client.domain.ClienteRapido;
import co.unicauca.apptimarket.commons.domain.carritoDTO;
import java.util.ArrayList;

/**
 *
 * @author WINDOWS
 */
public class frmRecibo extends javax.swing.JFrame {
   
    /**
     * Creates new form frmRecibo
     */
    public frmRecibo() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public frmRecibo(ArrayList <carritoDTO> prmPago, ClienteRapido prmClienteRapido) {
        initComponents();
        setLocationRelativeTo(null);
        
        txtNombreComprador.setText(prmClienteRapido.getAtrNombre().trim());
        txtIDComprador.setText(prmClienteRapido.getAtrID().trim());
        txtDireccion.setText(prmClienteRapido.getAtrDireccion().trim());
        txtTelefono.setText(prmClienteRapido.getAtrTelefono().trim());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtIDComprador = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        txtNombreComprador = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        txtTelefono1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setText("Factura de compra");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(188, 11, 325, 47);

        jLabel5.setText("Nombre comprador:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 100, 95, 14);

        jLabel6.setText("ID comprador:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 130, 69, 14);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel7.setText("TOTAL A PAGAR ($):");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 375, 240, 32);
        getContentPane().add(txtIDComprador);
        txtIDComprador.setBounds(180, 130, 230, 20);

        jLabel8.setText("Dirección de domicilio:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 160, 104, 14);
        getContentPane().add(txtDireccion);
        txtDireccion.setBounds(180, 160, 230, 20);
        getContentPane().add(txtNombreComprador);
        txtNombreComprador.setBounds(180, 100, 232, 20);

        jLabel9.setText("Número teléfono comprador:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 190, 138, 14);
        getContentPane().add(txtTelefono);
        txtTelefono.setBounds(180, 220, 230, 20);

        jTextField8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        getContentPane().add(jTextField8);
        jTextField8.setBounds(254, 372, 249, 38);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 258, 673, 96);

        jLabel10.setText("Infotmación de la compra");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(20, 220, 121, 14);
        getContentPane().add(txtTelefono1);
        txtTelefono1.setBounds(180, 190, 230, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRecibo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRecibo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRecibo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRecibo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRecibo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtIDComprador;
    private javax.swing.JTextField txtNombreComprador;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTelefono1;
    // End of variables declaration//GEN-END:variables
}
